from __future__ import annotations

LANGUAGE_LABELS: dict[str, dict[str, str]] = {
    "uz": {
        "header_tagline": "Biznesingiz uchun aqlli texnologiyalar",
        "offer_label": "Siz uchun maxsus taklif:",
        "services_title": "Bizning xizmatlar",
        "service_ready_title": "Tayyor sun'iy intellekt agentlari",
        "service_ready_body": "Mijozlarga kecha-kunduz javob beruvchi, sotuvga yordam beruvchi va murojaatlarni qabul qiluvchi aqlli tizimlar.",
        "service_custom_title": "Maxsus sun'iy intellekt yechimlari",
        "meeting_label": "Tanishuv uchrashuvi uchun taklif:",
        "meeting_link_prefix": "Qulay vaqt tanlash:",
        "meeting_button": "Tanishuv uchrashuvini belgilash",
        "contact_button": "Biz bilan bog'laning",
        "cta_prompt": "Bepul konsultatsiya yoki namoyishni ko'rishni xohlaysizmi?",
        "mailto_subject": "Hamkorlik",
        "rights_text": "Barcha huquqlar himoyalangan.",
        "location_text": "Toshkent sh., O'zbekiston",
        "website_label": "Veb-saytimiz",
        "contact_label": "Aloqa",
        "custom_offer_title": "Maxsus sun'iy intellekt yechimlari",
        "closing_text": "Hurmat bilan",
    },
    "ru": {
        "header_tagline": "Умные технологии для вашего бизнеса",
        "offer_label": "Специальное предложение для вас:",
        "services_title": "Наши услуги",
        "service_ready_title": "Готовые интеллектуальные агенты",
        "service_ready_body": "Умные системы, которые круглосуточно отвечают клиентам, помогают продажам и принимают обращения.",
        "service_custom_title": "Индивидуальные решения на базе искусственного интеллекта",
        "meeting_label": "Предложение по ознакомительной встрече:",
        "meeting_link_prefix": "Выбрать удобное время:",
        "meeting_button": "Назначить ознакомительную встречу",
        "contact_button": "Связаться с нами",
        "cta_prompt": "Хотите получить бесплатную консультацию или демонстрацию?",
        "mailto_subject": "Сотрудничество",
        "rights_text": "Все права защищены.",
        "location_text": "Ташкент, Узбекистан",
        "website_label": "Наш сайт",
        "contact_label": "Контакты",
        "custom_offer_title": "Индивидуальные решения на базе искусственного интеллекта",
        "closing_text": "С уважением",
    },
}

CAMPAIGN_COPY: dict[str, dict[str, dict[str, dict[str, str]]]] = {
    "uz": {
        "general": {
            "A": {
                "subject": "{company_name} uchun operatsion xarajatlarni kamaytirish taklifi",
                "preheader": "Mijozlar bilan muloqotni kecha-kunduz avtomatlashtirish imkoniyati.",
                "headline": "Mijozlarga javob berish tezligini oshiring",
                "intro": "Biz {company_name} faoliyatini ko'rib chiqdik va mijozlar murojaatini tezroq qayta ishlash uchun aniq imkoniyatni ko'rdik.",
                "problem": "Ko'plab kompaniyalarda xodimlar bir xil savollarga javob berish va murojaatlarni saralashga ko'p vaqt sarflaydi.",
                "solution": "{brand_name} tizimi murojaatlarni qabul qiladi, ehtiyojni aniqlaydi va jamoangizga tayyor mijozlarni uzatadi.",
                "cta": "{reply_phrase}, sizga qisqa taqdimot va amaliy ssenariyni yuboramiz.",
            },
            "B": {
                "subject": "{company_name} uchun mijozlar bilan ishlashni avtomatlashtirish taklifi",
                "preheader": "Kamroq xarajat, tezroq javob va ko'proq natija.",
                "headline": "Murojaatlarni nazoratdan chiqarmang",
                "intro": "{company_name} kabi o'sayotgan bizneslarda har bir kechikkan javob yo'qolgan imkoniyatga aylanishi mumkin.",
                "problem": "Savdo va xizmat ko'rsatish sohalarida kunduzgi va tungi murojaatlar jamoaga ortiqcha bosim beradi.",
                "solution": "{brand_name} tizimi savollarni qabul qiladi, dastlabki saralashni bajaradi va menejerga tayyor ma'lumot uzatadi.",
                "cta": "{reply_phrase}, sizga mos yechimlarni birgalikda ko'rib chiqamiz.",
            },
        },
        "healthcare": {
            "A": {
                "subject": "{company_name} klinikasi uchun qabul jarayonini avtomatlashtirish taklifi",
                "preheader": "Bemor yozuvlari va navbatni tartibga solish bo'yicha yechim.",
                "headline": "Bemorlarni qabul qilishni soddalashtiring",
                "intro": "Biz tibbiyot markazlari uchun qo'ng'iroq va yozuv oqimini avtomatlashtiradigan yechimlar yaratamiz.",
                "problem": "Klinikalarda bemorlarning tez javob kutishi va navbatni qo'lda boshqarish ko'p vaqt oladi.",
                "solution": "{brand_name} yordamchisi yozuvlarni qabul qiladi, ko'p so'raladigan savollarga javob beradi va administrator yukini kamaytiradi.",
                "cta": "{reply_phrase}, sizga klinika uchun mos ssenariyni yuboramiz.",
            },
            "B": {
                "subject": "{company_name} uchun bemorlarni yozib qo'yishni avtomatlashtirish taklifi",
                "preheader": "Qo'ng'iroqlarni yo'qotmasdan qabulni tartibga soling.",
                "headline": "Bemor oqimini yo'qotmang",
                "intro": "{company_name} jamoasi uchun bemorlarni yozib qo'yish va navbatni boshqarishni avtomatlashtirish mumkin.",
                "problem": "Kech javob yoki tushib qolgan qo'ng'iroq klinika obro'si va natijasiga salbiy ta'sir qiladi.",
                "solution": "{brand_name} tizimi yozuvlarni qabul qiladi, savollarga javob beradi va qabul jarayonini tezlashtiradi.",
                "cta": "{reply_phrase}, sizga amaliy misollar va ulanish variantlarini yuboramiz.",
            },
        },
        "education": {
            "A": {
                "subject": "{company_name} uchun yangi o'quvchilar oqimini oshirish taklifi",
                "preheader": "Reklamadan kelgan so'rovlarga bir necha soniyada javob berish imkoniyati.",
                "headline": "Qiziqqan mijozlarni yo'qotmang",
                "intro": "O'quv markazlari uchun eng qimmat yo'qotishlardan biri bu qiziqqan foydalanuvchiga kech javob berishdir.",
                "problem": "Ko'p markazlarda reklama orqali kelgan so'rovlar kech qayta ishlanadi va yozilish foizi pasayadi.",
                "solution": "{brand_name} tizimi yangi so'rovni darhol kutib oladi, kurs bo'yicha ma'lumot beradi va yozib qo'yishga yordam beradi.",
                "cta": "{reply_phrase}, sizga markaz uchun mos ssenariyni yuboramiz.",
            },
            "B": {
                "subject": "{company_name} uchun o'quvchilarga xizmat ko'rsatishni tezlashtirish taklifi",
                "preheader": "So'rovdan yozilishgacha bo'lgan yo'lni soddalashtiring.",
                "headline": "Har bir murojaatni natijaga aylantiring",
                "intro": "{company_name} reklama va kiruvchi so'rovlardan maksimal foyda olish uchun tezkor birinchi javobga muhtoj bo'lishi mumkin.",
                "problem": "Agar so'rovlar kech qayta ishlansa, ota-onalar yoki talabalar boshqa markazni tanlab ketadi.",
                "solution": "{brand_name} tizimi kurslar, narxlar va jadval bo'yicha savollarga javob berib, menejerga faqat tayyor mijozni uzatadi.",
                "cta": "{reply_phrase}, sizga ishlaydigan aloqa ssenariysini yuboramiz.",
            },
        },
        "custom": {
            "A": {
                "subject": "{company_name} uchun maxsus sun'iy intellekt yechimlari",
                "preheader": "Biznes jarayonlarini sizga mos tarzda raqamlashtirish taklifi.",
                "headline": "Sizga mos, noldan qurilgan yechim",
                "intro": "Biz {company_name} faoliyatini samaraliroq qilish uchun tayyor vositalar bilan cheklanmaymiz.",
                "problem": "Ko'plab bizneslarda oddiy vosita yetarli bo'lmaydi va ichki jarayonlar uchun moslashtirilgan avtomatlashtirish kerak bo'ladi.",
                "solution": "{brand_name} jamoasi ichki tizimlar bilan ulanish, hujjatlar bilan ishlash va xodimlar uchun yordamchi vositalarni noldan quradi.",
                "cta": "{reply_phrase}, qaysi yo'nalish sizga qiziq ekanini aniqlab, tanishuv uchrashuvini belgilaymiz.",
            },
            "B": {
                "subject": "{company_name} uchun sun'iy intellekt va raqamlashtirish taklifi",
                "preheader": "Tayyor yechimlar ham, maxsus ishlab chiqish ham bir joyda.",
                "headline": "Tayyor vositalar ham, maxsus yechimlar ham",
                "intro": "Biz {company_name} uchun tayyor agentlar bilan birga, noodatiy ehtiyojlar uchun maxsus arxitektura ham taklif qilamiz.",
                "problem": "Murakkab ichki jarayonlar yoki hujjat oqimlari bo'lsa, oddiy vositalar ularni to'liq yopib bera olmaydi.",
                "solution": "{brand_name} jamoasi jarayonni tahlil qilib, mos ulanish va maxsus modulni ishlab chiqadi.",
                "cta": "{reply_phrase}, eng mos yo'nalishni birgalikda tanlaymiz.",
            },
        },
        "logistics": {
            "A": {
                "subject": "{company_name} uchun logistika jarayonlarini avtomatlashtirish taklifi",
                "preheader": "Buyurtma, yo'nalish va yuk holati bo'yicha murojaatlarni soddalashtiring.",
                "headline": "Logistika jarayonlarini tezroq boshqaring",
                "intro": "Logistika kompaniyalarida tezkor koordinatsiya va aniq javob operatsion samaradorlikka bevosita ta'sir qiladi.",
                "problem": "Xodimlar ko'p vaqtini takroriy savollar, yuk holati va yo'nalish bo'yicha qo'lda javob berishga sarflaydi.",
                "solution": "{brand_name} tizimi buyurtmalarni qabul qilish, holatni aytish va operator yukini kamaytirishga yordam beradi.",
                "cta": "{reply_phrase}, sizga logistika uchun mos ssenariyni yuboramiz.",
            },
            "B": {
                "subject": "{company_name} uchun yuk jarayonlarini soddalashtirish taklifi",
                "preheader": "Mijoz va operator orasidagi takroriy aloqalarni qisqartiring.",
                "headline": "Jarayonni kecha-kunduz nazoratda ushlang",
                "intro": "{company_name} uchun qo'ng'iroq, buyurtma va holat savollarini avtomatlashtirish orqali jamoa vaqtini tejash mumkin.",
                "problem": "Logistika jamoalarida aynan bir xil savollarga qayta-qayta javob berish mijoz tajribasini sekinlashtiradi.",
                "solution": "{brand_name} tizimi buyurtma oqimini saralaydi, mijozga tez javob beradi va ichki jamoaga tayyor ma'lumot uzatadi.",
                "cta": "{reply_phrase}, sizga qisqa ko'rsatma va foydalanish ssenariysini yuboramiz.",
            },
        },
    },
    "ru": {
        "general": {
            "A": {
                "subject": "Предложение по снижению операционных расходов для {company_name}",
                "preheader": "Возможность автоматизировать общение с клиентами круглосуточно.",
                "headline": "Ускорьте ответы клиентам",
                "intro": "Мы изучили деятельность {company_name} и увидели возможность быстрее обрабатывать обращения клиентов.",
                "problem": "Во многих компаниях сотрудники тратят много времени на одинаковые вопросы и первичную обработку обращений.",
                "solution": "{brand_name} принимает обращения, определяет потребность клиента и передает вашей команде уже подготовленные запросы.",
                "cta": "{reply_phrase}, и мы отправим короткую презентацию и практический сценарий.",
            },
            "B": {
                "subject": "Предложение по автоматизации работы с клиентами для {company_name}",
                "preheader": "Меньше затрат, быстрее ответ и больше результата.",
                "headline": "Не упускайте обращения",
                "intro": "Для растущего бизнеса, такого как {company_name}, каждый поздний ответ может означать потерянную возможность.",
                "problem": "В продажах и сервисе дневные и ночные обращения создают лишнюю нагрузку на команду.",
                "solution": "{brand_name} принимает обращения, выполняет первичную сортировку и передает менеджеру готовую информацию.",
                "cta": "{reply_phrase}, и мы обсудим подходящие именно вам решения.",
            },
        },
        "healthcare": {
            "A": {
                "subject": "Предложение по автоматизации приема для клиники {company_name}",
                "preheader": "Решение для записи пациентов и управления очередью.",
                "headline": "Упростите прием пациентов",
                "intro": "Мы создаем решения для медицинских центров, которые автоматизируют поток звонков и запись пациентов.",
                "problem": "В клиниках ожидание быстрого ответа и ручное управление очередью отнимают много времени.",
                "solution": "{brand_name} принимает записи, отвечает на частые вопросы и снижает нагрузку на администратора.",
                "cta": "{reply_phrase}, и мы отправим подходящий для вашей клиники сценарий.",
            },
            "B": {
                "subject": "Предложение по автоматизации записи пациентов для {company_name}",
                "preheader": "Организуйте прием без потери звонков.",
                "headline": "Не теряйте поток пациентов",
                "intro": "Для команды {company_name} можно автоматизировать запись пациентов и управление очередью.",
                "problem": "Поздний ответ или пропущенный звонок негативно влияют на репутацию и результат клиники.",
                "solution": "{brand_name} принимает записи, отвечает на вопросы и ускоряет процесс приема.",
                "cta": "{reply_phrase}, и мы пришлем практические примеры и варианты подключения.",
            },
        },
        "education": {
            "A": {
                "subject": "Предложение по увеличению потока учеников для {company_name}",
                "preheader": "Возможность отвечать на рекламные обращения за считанные секунды.",
                "headline": "Не теряйте заинтересованных клиентов",
                "intro": "Для учебных центров одна из самых дорогих потерь — это поздний ответ заинтересованному человеку.",
                "problem": "Во многих центрах заявки из рекламы обрабатываются поздно, и доля записавшихся снижается.",
                "solution": "{brand_name} сразу принимает новую заявку, дает информацию о курсах и помогает оформить запись.",
                "cta": "{reply_phrase}, и мы отправим подходящий для вашего центра сценарий.",
            },
            "B": {
                "subject": "Предложение по ускорению работы с учениками для {company_name}",
                "preheader": "Сделайте путь от обращения до записи проще.",
                "headline": "Преобразуйте каждое обращение в результат",
                "intro": "Чтобы получать максимум от рекламы и входящих обращений, {company_name} может быть важен быстрый первый ответ.",
                "problem": "Если обращения обрабатываются поздно, родители и ученики выбирают другой центр.",
                "solution": "{brand_name} отвечает на вопросы о курсах, ценах и расписании и передает менеджеру уже подготовленного клиента.",
                "cta": "{reply_phrase}, и мы отправим вам рабочий сценарий общения.",
            },
        },
        "custom": {
            "A": {
                "subject": "Индивидуальные решения на базе искусственного интеллекта для {company_name}",
                "preheader": "Предложение по цифровизации процессов под ваши задачи.",
                "headline": "Решение, созданное под вас с нуля",
                "intro": "Мы не ограничиваемся готовыми инструментами и подходим к задачам {company_name} индивидуально.",
                "problem": "Во многих компаниях стандартного инструмента недостаточно, и для внутренних процессов нужна точная автоматизация.",
                "solution": "{brand_name} создает с нуля решения для внутренних систем, работы с документами и помощников для сотрудников.",
                "cta": "{reply_phrase}, и мы определим интересующее вас направление и назначим ознакомительную встречу.",
            },
            "B": {
                "subject": "Предложение по искусственному интеллекту и цифровизации для {company_name}",
                "preheader": "Готовые решения и индивидуальная разработка в одном месте.",
                "headline": "И готовые инструменты, и индивидуальные решения",
                "intro": "Для {company_name} мы можем предложить как готовые интеллектуальные помощники, так и архитектуру под нестандартные задачи.",
                "problem": "Если внутри бизнеса есть сложные процессы или большой поток документов, стандартных инструментов часто недостаточно.",
                "solution": "{brand_name} анализирует процесс, подбирает подключения и разрабатывает индивидуальный модуль под вашу задачу.",
                "cta": "{reply_phrase}, и мы вместе выберем наиболее подходящее направление.",
            },
        },
        "logistics": {
            "A": {
                "subject": "Предложение по автоматизации логистических процессов для {company_name}",
                "preheader": "Упростите обращения по заказам, маршрутам и статусу груза.",
                "headline": "Ускорьте логистические процессы",
                "intro": "В логистике быстрая координация и точный ответ напрямую влияют на эффективность работы.",
                "problem": "Сотрудники тратят много времени на повторяющиеся вопросы о статусе груза, маршруте и заказе.",
                "solution": "{brand_name} помогает принимать заказы, сообщать статус и снижать нагрузку на операторов.",
                "cta": "{reply_phrase}, и мы отправим подходящий сценарий для логистики.",
            },
            "B": {
                "subject": "Предложение по упрощению грузовых процессов для {company_name}",
                "preheader": "Сократите повторяющиеся контакты между клиентом и оператором.",
                "headline": "Держите процессы под контролем круглосуточно",
                "intro": "Для {company_name} можно автоматизировать звонки, заказы и вопросы по статусу, экономя время команды.",
                "problem": "Когда логистическая команда постоянно отвечает на одни и те же вопросы, путь клиента замедляется.",
                "solution": "{brand_name} сортирует поток заказов, быстро отвечает клиенту и передает команде готовую информацию.",
                "cta": "{reply_phrase}, и мы пришлем краткий сценарий использования.",
            },
        },
    },
}
